name: Golang build

inputs:
  APP_NAME:
    description: "Name of the app"
    required: false
    default: "${{ github.event.repository.name }}"
  RELEASE_BODY:
    description: "Text for release"
    required: false


permissions:
  contents: write

runs:
  using: "composite"
  steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Move all artifacts to the current directory
      shell: bash
      run: |
        mv ./*/${{ inputs.APP_NAME }}_* ./

    - shell: bash
      run: |
        echo "${{ inputs.RELEASE_BODY }}"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: "${{ inputs.RELEASE_BODY }}"
        prerelease: false
        fail_on_unmatched_files: true
        files: |
          ${{ inputs.APP_NAME }}_*
