name: Golang build

inputs:
  GITHUB_TOKEN:
    description: "Token that is allowed to create releases"
    required: false
  APP_NAME:
    description: "Name of the app"
    required: false
    default: "${{ github.event.repository.name }}"

permissions:
  contents: write

runs:
  using: "composite"
  steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2

    - name: Move all artifacts to the current directory
      shell: bash
      run: |
        mv ./*/${{ inputs.APP_NAME }}_* ./

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.md # TODO only last part
        prerelease: false
        fail_on_unmatched_files: true
        files: |
          ${{ inputs.APP_NAME }}_*
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
